### PR TITLE
Use nbsphinx to handle notebook-based tutorials 

### PR DESCRIPTION
**Pull request by QuLogic**
This will generate the pages directly from the `ipynb` files, and thus means there's no need to hold on to a bunch of pre-generated files in the repo. Additionally, cross references can use Sphinx linking and thus result in links that are more self-contained.

### CODE REVIEW

**Review by ResidentMario — APPROVED** [review]
Looks good, works locally. Thanks!

**Comment by ResidentMario** [comment]
@QuLogic After merging this PR, everything works as expected locally. However, after deploying it to the web, we have the curious problem that the sidebar links to https://residentmario.github.io/geoplot/quickstart/Quickstart.html, whilst the document is actually served at https://residentmario.github.io/geoplot/quickstart/quickstart.html.

As a result, clicking on `Quickstart` in the sidebar in the master docs (https://residentmario.github.io/geoplot/index.html#) currently takes you to a 404 page.

The reasons why this happens are too baroque for me to understand, but on some level have to do with how word case is handled on macOS. Something like this happened once before: #175. I'm going to hope it goes away this time also (as it did then) as this is going to be a PITA to fix by hand.

**Comment by QuLogic** [comment]
Yes, case-preserving file systems can be weird. We could rename it lower case if that helps?

**Comment by ResidentMario** [comment]
Yeah your hunch was right, renaming the file (`Quickstart.ipynb -> quickstart.ipynb`) and changing `toctree` to match did the trick.

**Pull request merged**
